// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioytvvtkmslszgmlgyar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveXR2dnRrbXNsc3pnbWxneWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTM4MDEsImV4cCI6MjA2OTQyOTgwMX0.BvPmN8h_0IMY0evvLMu8L2SdTD9JZyH-ewu-ql2DtbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});